### ISSUE TITLE
Create a function to generate an md5 digest for a file

### ISSUE THREAD

**Issue by humphd** [josh0588/go-file-utils#2]
We need to generate an [MD5 digest](https://en.wikipedia.org/wiki/MD5) for a file at the given path.  For example, given a path like `"/home/kim/mydata.txt"`, which contains the text `The quick brown fox jumps over the lazy dog`, the function should return the string `"9e107d9d372bb6826bd81d3542a419d6"`

**Comment by humphd** [comment]
I haven't used Go before, but it looks like this might be doable with https://golang.org/pkg/crypto/md5/

**Comment by josh0588** [comment]
ae6a26fe738d87ec971fc8305ce904217fbfb7a5
added function for generating an md5 digest
